# Generated by Django 3.0.5 on 2020-04-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Movie')),
            ],
        ),
    ]
